### ISSUE TITLE
Ansible error on 'add instance'

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-multiinstance-backend#21] opened 2017-05-05 12:42 UTC
I got an error on adding an instance. See in this log
[ansible.26ca9663148741b685c33379881e0f13.log.json.txt](https://github.com/OpenSlides/openslides-multiinstance-backend/files/979010/ansible.26ca9663148741b685c33379881e0f13.log.json.txt)

The problem is, that the rocket container isn't ready, but in the next step the skript wants to execute the collectstatic. I can manually run this command about 10 seconds later and it work. So a pause is needed, or somehow wait until the container is fully started.

**Comment by boehlke** [comment] 2017-05-17 05:43
This will be fixed soon.

**Comment by boehlke** [comment] 2017-10-18 11:25
This is a duplicate of #22 , will be fixed there

**Closed as completed by boehlke** 2017-10-18 11:25 UTC
